[project]

name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aerich>=0.9.1",
    "fastapi[standard]>=0.116.1",
    "tortoise>=0.1.1",
    "tortoise-orm>=0.25.1",
]
